language: python
python:
  - "3.6"      # current default Python on Travis CI
install:
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/requirements-cpu.txt
# command to run tests
script:
  - pytest --cov-config .coveragerc --cov=node_api_commons tests

after_success:
  - codecov